name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12 UTC everyday
    - cron: "0 1 * * *"

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: ApoorvTyagi/quote-readme@main
        with:
          OPTION: both 
